before_script:
  - ls -l

build_esticonsole:
  script:
    - go get github.com/c9s/goprocinfo/linux
    - go get google.golang.org/grpc
    - go get github.com/jroimartin/gocui
    - go get github.com/nu7hatch/gouuid
    - go get github.com/howeyc/gopass
    - ./buildEverything.sh .

  artifacts:
    untracked: false
    name: "EstiConsole_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - bin/
