language: go

go:
  - "1.10.x"
  - master

install: true

matrix:
  # It's ok if our code fails on unstable development versions of Go.
  allow_failures:
    - go: master
  # Don't wait for tip tests to finish. Mark the test run green if the
  # tests pass on the stable versions of Go.
  fast_finish: true

before_install:
  - go get -t github.com/c9s/goprocinfo/linux
  - go get -t google.golang.org/grpc
  - go get -t github.com/jroimartin/gocui
  - go get -t github.com/nu7hatch/gouuid
  - go get -t github.com/howeyc/gopass

script:
  - ./buildServer.sh

notifications:
  email: false