// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cliotesky.proto

/*
Package cliotesky is a generated protocol buffer package.

It is generated from these files:
	cliotesky.proto

It has these top-level messages:
	Empty
	Token
	ClioteMessage
	ClioteResponse
	ClioteSend
	AuthRequest
*/
package cliotesky

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Token struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ClioteMessage struct {
	Data       []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Identifier string `protobuf:"bytes,2,opt,name=identifier" json:"identifier,omitempty"`
	Sender     string `protobuf:"bytes,3,opt,name=sender" json:"sender,omitempty"`
}

func (m *ClioteMessage) Reset()                    { *m = ClioteMessage{} }
func (m *ClioteMessage) String() string            { return proto.CompactTextString(m) }
func (*ClioteMessage) ProtoMessage()               {}
func (*ClioteMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ClioteMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ClioteMessage) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *ClioteMessage) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

type ClioteResponse struct {
	Data []*ClioteMessage `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *ClioteResponse) Reset()                    { *m = ClioteResponse{} }
func (m *ClioteResponse) String() string            { return proto.CompactTextString(m) }
func (*ClioteResponse) ProtoMessage()               {}
func (*ClioteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ClioteResponse) GetData() []*ClioteMessage {
	if m != nil {
		return m.Data
	}
	return nil
}

type ClioteSend struct {
	Data       []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Identifier string `protobuf:"bytes,2,opt,name=identifier" json:"identifier,omitempty"`
	Recipient  string `protobuf:"bytes,3,opt,name=recipient" json:"recipient,omitempty"`
}

func (m *ClioteSend) Reset()                    { *m = ClioteSend{} }
func (m *ClioteSend) String() string            { return proto.CompactTextString(m) }
func (*ClioteSend) ProtoMessage()               {}
func (*ClioteSend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ClioteSend) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ClioteSend) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *ClioteSend) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

type AuthRequest struct {
	User     string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *AuthRequest) Reset()                    { *m = AuthRequest{} }
func (m *AuthRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()               {}
func (*AuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AuthRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*Token)(nil), "Token")
	proto.RegisterType((*ClioteMessage)(nil), "ClioteMessage")
	proto.RegisterType((*ClioteResponse)(nil), "ClioteResponse")
	proto.RegisterType((*ClioteSend)(nil), "ClioteSend")
	proto.RegisterType((*AuthRequest)(nil), "AuthRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ClioteSkyService service

type ClioteSkyServiceClient interface {
	Request(ctx context.Context, in *Token, opts ...grpc.CallOption) (*ClioteResponse, error)
	Send(ctx context.Context, in *ClioteSend, opts ...grpc.CallOption) (*Empty, error)
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*Token, error)
}

type clioteSkyServiceClient struct {
	cc *grpc.ClientConn
}

func NewClioteSkyServiceClient(cc *grpc.ClientConn) ClioteSkyServiceClient {
	return &clioteSkyServiceClient{cc}
}

func (c *clioteSkyServiceClient) Request(ctx context.Context, in *Token, opts ...grpc.CallOption) (*ClioteResponse, error) {
	out := new(ClioteResponse)
	err := grpc.Invoke(ctx, "/ClioteSkyService/Request", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clioteSkyServiceClient) Send(ctx context.Context, in *ClioteSend, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/ClioteSkyService/Send", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clioteSkyServiceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := grpc.Invoke(ctx, "/ClioteSkyService/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ClioteSkyService service

type ClioteSkyServiceServer interface {
	Request(context.Context, *Token) (*ClioteResponse, error)
	Send(context.Context, *ClioteSend) (*Empty, error)
	Auth(context.Context, *AuthRequest) (*Token, error)
}

func RegisterClioteSkyServiceServer(s *grpc.Server, srv ClioteSkyServiceServer) {
	s.RegisterService(&_ClioteSkyService_serviceDesc, srv)
}

func _ClioteSkyService_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClioteSkyServiceServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClioteSkyService/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClioteSkyServiceServer).Request(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClioteSkyService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClioteSend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClioteSkyServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClioteSkyService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClioteSkyServiceServer).Send(ctx, req.(*ClioteSend))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClioteSkyService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClioteSkyServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClioteSkyService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClioteSkyServiceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClioteSkyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ClioteSkyService",
	HandlerType: (*ClioteSkyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _ClioteSkyService_Request_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _ClioteSkyService_Send_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _ClioteSkyService_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cliotesky.proto",
}

func init() { proto.RegisterFile("cliotesky.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x55, 0x69, 0x92, 0xd2, 0x4b, 0x69, 0x91, 0x85, 0x50, 0x14, 0x0a, 0x42, 0x9e, 0x3a, 0x79,
	0x28, 0xac, 0x0c, 0x08, 0x31, 0xb2, 0xa4, 0x6c, 0x48, 0x48, 0x21, 0x39, 0xc0, 0x0a, 0xd8, 0xa9,
	0xed, 0x80, 0xf2, 0xef, 0x51, 0x2e, 0xa6, 0x2d, 0x8c, 0xdd, 0xee, 0x9e, 0x7d, 0xef, 0xe3, 0x0e,
	0x66, 0xc5, 0x87, 0xd4, 0x0e, 0x6d, 0xd5, 0x8a, 0xda, 0x68, 0xa7, 0xf9, 0x08, 0xc2, 0xfb, 0xcf,
	0xda, 0xb5, 0xfc, 0x1c, 0xc2, 0x47, 0x5d, 0xa1, 0x62, 0x27, 0x10, 0xba, 0xae, 0x48, 0x06, 0x97,
	0x83, 0xc5, 0x38, 0xeb, 0x1b, 0xfe, 0x04, 0x47, 0x77, 0x34, 0xfa, 0x80, 0xd6, 0xe6, 0x6f, 0xc8,
	0x18, 0x04, 0x65, 0xee, 0x72, 0xfa, 0x35, 0xc9, 0xa8, 0x66, 0x17, 0x00, 0xb2, 0x44, 0xe5, 0xe4,
	0xab, 0x44, 0x93, 0x1c, 0xd0, 0xfc, 0x0e, 0xc2, 0x4e, 0x21, 0xb2, 0xa8, 0x4a, 0x34, 0xc9, 0x90,
	0xde, 0x7c, 0xc7, 0xaf, 0x61, 0xda, 0x93, 0x67, 0x68, 0x6b, 0xad, 0x2c, 0x32, 0xbe, 0x61, 0x1f,
	0x2e, 0xe2, 0xe5, 0x54, 0xfc, 0xd1, 0xee, 0xd5, 0xf8, 0x33, 0x40, 0x0f, 0xaf, 0x50, 0x95, 0x7b,
	0xf9, 0x99, 0xc3, 0xd8, 0x60, 0x21, 0x6b, 0x89, 0xca, 0x79, 0x4b, 0x5b, 0x80, 0xdf, 0x40, 0x7c,
	0xdb, 0xb8, 0xf7, 0x0c, 0xd7, 0x0d, 0x5a, 0xd7, 0x09, 0x34, 0x16, 0x8d, 0x5f, 0x0b, 0xd5, 0x2c,
	0x85, 0xc3, 0x3a, 0xb7, 0xf6, 0x5b, 0x9b, 0xd2, 0xd3, 0x6f, 0xfa, 0xe5, 0x1a, 0x8e, 0xbd, 0xbd,
	0xaa, 0x5d, 0xa1, 0xf9, 0x92, 0x45, 0x17, 0x6b, 0xf4, 0x4b, 0x17, 0x09, 0x5a, 0x77, 0x3a, 0x13,
	0xff, 0xa2, 0x9f, 0x41, 0x40, 0x81, 0x62, 0xb1, 0x4d, 0x97, 0x46, 0x82, 0xae, 0xc4, 0xe6, 0x10,
	0x74, 0x9e, 0xd8, 0x44, 0xec, 0x58, 0x4b, 0x3d, 0xd7, 0x4b, 0x44, 0x37, 0xbd, 0xfa, 0x09, 0x00,
	0x00, 0xff, 0xff, 0x70, 0x90, 0x24, 0x8d, 0xe6, 0x01, 0x00, 0x00,
}
